# -*- org-confirm-babel-evaluate: nil -*-
#+TITLE: ParkinsonPathAI (Working title) - AI Models for Pathway Analysis in Parkinson’s Disease

#+Author: Sam Neaves

* Introduction

This project focuses on analyzing single-cell transcriptomic data from
brain cells of both control and Parkinson’s disease donors. Our goal
is to characterize the complex interplay between the RAS and dopamine
pathways, we will attempt to do this using symbolic AI techniques. By employing methods like
descriptive rule induction, causal analysis, and model
building/repair, we aim to identify and understand unique cell states
associated with Parkinson’s disease.

Our approach reconciles gene networks with experimental data, allowing
us to reason about network consistency and potentially discover key
molecular signatures involved in disease progression. This repository will
contain code, data preprocessing steps, and model implementation
details for this exploratory analysis.

This is an open scientific project, actively developed in the
open-source community and a continuous work in progress. As the
results are preliminary, they may evolve over time with further
analysis and validation. If you spot any errors or have suggestions,
please feel free to open an issue. Contributions and feedback from the
community are welcome to help improve and refine our understanding of
the RAS and dopamine pathways in Parkinson’s disease.

* Data

Biological cell samples were collected postmortem from the ventral
substantia nigra of seven control samples, nine Parkinson's disease
samples, and four samples from patients with Incidental Lewy Body
Disorder. The nuclei of these cells were extracted and sequenced,
totaling 23,885 nuclei. The sequecning was deep and full
length. [INSERT DETALS OF SEQUENCING TECH OR REFERNCE]

** System biology approach

Our approach to this analysis is based on symbolic systems biology.
In systems biology we aim to understand and model the biological
reality at a system level, that is understanding how many aspects of
biology interact to cause our observations. This is in conrast to
looking at specific decompatialised observations. Symbolic system
biology differs from quantitive symbolic biology in the level of
abstraction.
The use of discrete symbols to represent aspects of the system rather
than specific quantitites has a number of advantages which we seek to
exploit.
Firstly, the abstraction of measured data to symbols is a way to
handle noise.
Secondly, the abstraction reduces the size of state space that we are examining.
This means that certain computational methods become tractable.
Thirdly, as our aim is to understand what is happening and ultimatly
control the system.  It is therefore important that our models and their dynamics
are intertplble, so that suggested interventions and there
consequences can be ratified in a laboratory setting.

Forthyly, there is evidence that symbolic abstraction is sufficent to model the dynamics in
many cases.

Biological reality is extremely complicated.

The basic idea of DNA -> (transcribed) RNA -> (translated) Protein,
which takes part in a series of biochemical reactions to build,
maintain and controll cells is
sound and present however the details around transcription,
translation and metabolic pathways ultimatly leading to disease are
complex and what we seek to understand.

In somatic cells the DNA is immutable as they replicate into daughter
cells.
The differnce between cells .
Cell differnation.
Gene regulatory networks.

Transcription can be bursty.
Alternative splicing
Protein complex formation. - chaperones.
Epigentics, methylation and histone access.


*** Intreptation of sequence data as instances in state space.

In our analysis of transcriptome from nuclei, previous work has
identified cell types using x method.
In addition cell states have been identified by y method.

** RAS MAPK pathway

In this work we are intrested in these pathways and the interplay.
In order to get a list of genes that we are intreseted in and there
interactions, we first manually curate a list of genes by augmenting a
list of querying for list of pathway genes.

The intial list is :

Raas genes:
#+begin_src bash :results output :exports both
  cat ./data/initial_gene_list_files/raas_genes.txt
#+end_src

#+RESULTS:
#+begin_example
ACE
ADCY
AGTR1
AGTR2
AGT
ATF2
CCL2
CCL5
DAG1
ELK1
ERK1
ERK2
FOS
GNAQ
GRB2
IP3
JAK2
JNK
JUN
MAP2K1
MAP2K2
MAP2K4
MAP3K1
NFKB1
NO
NOX1
MAPK
PAK
PGE2
PI3K
PIP2
PKA
PKC
PLCG1
PTGER2
PTK2
PTK2B
PTPN6
RAC1
RAF1
HRAS
KRAS
REN
SHC1
SOS1
STAT1
STAT3
TNF
#+end_example

Dopamine KEGG pathway:

#+begin_src bash :results output :exports both
  cat ./data/initial_gene_list_files/DopamineKEGGpathway.txt
#+end_src

#+RESULTS:
#+begin_example
AKT3
CREB3
GNB5
ADCY5
COMT
CREB1
ATF2
ATF6B
MAPK14
CREB3L4
CALML6
DDC
DRD1
DRD2
DRD3
DRD4
DRD5
AKT1
AKT2
LRTOMT
PLCB1
FOS
GNAI1
GNAI2
GNAI3
GNAL
GNAQ
GNAO1
GNAS
GNB1
GNB2
GNB3
GNG3
GNG4
GNG5
GNG7
GNG10
GNG11
GNGT1
GNGT2
PPP2R3B
GRIA1
GRIA2
GRIA3
GRIA4
GRIN2A
GRIN2B
GSK3A
GSK3B
ITPR1
ITPR2
ITPR3
KCNJ3
KCNJ5
KCNJ6
KCNJ9
KIF5A
KIF5B
KIF5C
ARNTL
ARRB1
ARRB2
MAOA
MAOB
ATF4
CALY
GNG13
CALML5
PLCB2
PLCB3
PLCB4
GNG2
PPP1CA
PPP1CB
PPP1CC
PPP2R3C
PPP2CA
PPP2CB
PPP2R1A
PPP2R1B
PPP2R2A
PPP2R2B
PPP2R2C
PPP2R3A
PPP2R5A
PPP2R5B
PPP2R5C
PPP2R5D
PPP2R5E
PPP3CA
PPP3CB
PPP3CC
PRKACA
PRKACB
PRKACG
PRKCA
PRKCB
PRKCG
PPP2R2D
GNG12
MAPK8
MAPK11
MAPK13
GNB4
MAPK12
SCN1A
CREB3L2
SLC6A3
TH
CACNA1A
CACNA1B
CACNA1C
CACNA1D
CALM1
CALM2
CALM3
CALML3
CAMK2A
CAMK2B
CAMK2D
CAMK2G
PPP1R1B
CREB3L3
CREB3L1
CALML4
GNG8
CLOCK
CREB5
SLC18A2
SLC18A1
MAPK9
MAPK10

#+end_example

These were provided by Viola.

The intersection of these files is:
#+begin_src bash :results output :export both
  grep -Fxf ./data/initial_gene_list_files/DopamineKEGGpathway.txt ./data/initial_gene_list_files/raas_genes.txt
#+end_src

#+RESULTS:
: ATF2
: FOS
: GNAQ

The union of these files is:

#+begin_src bash :results output :export both
  cat ./data/initial_gene_list_files/DopamineKEGGpathway.txt ./data/initial_gene_list_files/raas_genes.txt | sort | uniq | tee ./data/initial_gene_list_files/initial_gene_list.txt
  wc -l ./data/initial_gene_list_files/initial_gene_list.txt
#+end_src

#+RESULTS:
#+begin_example

ACE
ADCY
ADCY5
AGT
AGTR1
AGTR2
AKT1
AKT2
AKT3
ARNTL
ARRB1
ARRB2
ATF2
ATF4
ATF6B
CACNA1A
CACNA1B
CACNA1C
CACNA1D
CALM1
CALM2
CALM3
CALML3
CALML4
CALML5
CALML6
CALY
CAMK2A
CAMK2B
CAMK2D
CAMK2G
CCL2
CCL5
CLOCK
COMT
CREB1
CREB3
CREB3L1
CREB3L2
CREB3L3
CREB3L4
CREB5
DAG1
DDC
DRD1
DRD2
DRD3
DRD4
DRD5
ELK1
ERK1
ERK2
FOS
GNAI1
GNAI2
GNAI3
GNAL
GNAO1
GNAQ
GNAS
GNB1
GNB2
GNB3
GNB4
GNB5
GNG10
GNG11
GNG12
GNG13
GNG2
GNG3
GNG4
GNG5
GNG7
GNG8
GNGT1
GNGT2
GRB2
GRIA1
GRIA2
GRIA3
GRIA4
GRIN2A
GRIN2B
GSK3A
GSK3B
HRAS
IP3
ITPR1
ITPR2
ITPR3
JAK2
JNK
JUN
KCNJ3
KCNJ5
KCNJ6
KCNJ9
KIF5A
KIF5B
KIF5C
KRAS
LRTOMT
MAOA
MAOB
MAP2K1
MAP2K2
MAP2K4
MAP3K1
MAPK
MAPK10
MAPK11
MAPK12
MAPK13
MAPK14
MAPK8
MAPK9
NFKB1
NO
NOX1
PAK
PGE2
PI3K
PIP2
PKA
PKC
PLCB1
PLCB2
PLCB3
PLCB4
PLCG1
PPP1CA
PPP1CB
PPP1CC
PPP1R1B
PPP2CA
PPP2CB
PPP2R1A
PPP2R1B
PPP2R2A
PPP2R2B
PPP2R2C
PPP2R2D
PPP2R3A
PPP2R3B
PPP2R3C
PPP2R5A
PPP2R5B
PPP2R5C
PPP2R5D
PPP2R5E
PPP3CA
PPP3CB
PPP3CC
PRKACA
PRKACB
PRKACG
PRKCA
PRKCB
PRKCG
PTGER2
PTK2
PTK2B
PTPN6
RAC1
RAF1
REN
SCN1A
SHC1
SLC18A1
SLC18A2
SLC6A3
SOS1
STAT1
STAT3
TH
TNF
     178 ./data/initial_gene_list_files/initial_gene_list.txt
#+end_example

Next in order to understand which other genes have known interactions
with this list and how this list is related we query pathway commons
using pybravo.

In order for pybravo to work it needs to be able to connect to a
sparql endpoint of pathway commons. Unforntly this resource can be
unrelaibly, however it is possible to set up a local sparql end point
by building a docker container. A docker recipe file is provided from
this github repo:
https://github.com/mkarikom/PathwayCommons-VOS#pathwaycommons-v12-on-virtuoso-7

With pybravo installed and an appropiate conda enivorment set up and
then pybravo set to point at our local instance of pathway commons
sparql end point we can query the resource.

We have set up the command to run from a biomake file (makeprog - in
the scripts dir)


#+begin_src bash :dir "./scripts/" :eval query :results output
  biomake "augment_gene_list" | tail -n 40
#+end_src

#+RESULTS:
#+begin_example
--- Upstream regulation network in 66.95 seconds ---
Number of nodes = 1339
Number of edges = 12032
SIF network written to ../data/pybravo_output/expanded.sif
Basic regulation reaction provenance written to ../data/pybravo_output/expanded-provenance.csv

| Node | Degree Centrality |
|------|------|
| NOG | 0.264 | 
| SP1 | 0.182 | 
| LEF1 | 0.17 | 
| MAZ | 0.168 | 
| TCF3 | 0.155 | 
| FOXO4 | 0.143 | 
| TGFB1 | 0.138 | 
| JUN | 0.136 | 
| MYC | 0.128 | 
| PAX4 | 0.123 | 

--- Network simplification in 2.4 seconds ---
SIF network written to ../data/pybravo_output/expanded-unified.sif
Basic regulation reaction provenance written to ../data/pybravo_output/expanded-unified-provenance.csv
Nodes after simplification = 1229
Edges after simplification = 11912

| Node | Degree Centrality |
|------|------|
| NOG | 0.276 | 
| DAND5 | 0.195 | 
| LEF1 | 0.182 | 
| MAZ | 0.178 | 
| TCF7L1 | 0.176 | 
| FOXO4 | 0.155 | 
| JUN | 0.151 | 
| TGFB1 | 0.149 | 
| HNF1A | 0.149 | 
| PVT1 | 0.139 | 


Target augment_gene_list built
#+end_example
